<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\Sclass;

class SclassSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Sclass::create([
            'color' => '#FF0000',
            'name_e' => 'Premier League',
            'name_es' => 'Premier League',
            'name_s' => 'EPL',
            'kind' => 1,
            'mode' => 1,
            'count_round' => 38,
            'curr_round' => 1,
            'curr_match_season' => '2024-2025',
            'sclass_pic' => 'https://upload.wikimedia.org/wikipedia/vi/thumb/f/f2/Premier_League_Logo.svg/1200px-Premier_League_Logo.svg.png',
            'if_stop' => 0,
            'count_group' => 1,
            'bf_simply_disp' => 1,
            'sclass_sequence' => 1,
            'info_id' => 1,
            'bf_if_disp' => 1,
            'if_have_sub' => false,
            'if_sort' => false,
            'if_have_paper' => false,
            'if_show_score' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Sclass::create([
            'color' => '#0000FF',
            'name_e' => 'La Liga',
            'name_es' => 'La Liga',
            'name_s' => 'LL',
            'kind' => 0,
            'mode' => 1,
            'count_round' => 38,
            'curr_round' => 1,
            'curr_match_season' => '2024-2025',
            'sclass_pic' => 'https://anh.24h.com.vn//upload/3-2016/images/2016-08-30/1472523173-laliga.jpg',
            'if_stop' => 0,
            'count_group' => 1,
            'bf_simply_disp' => 1,
            'sclass_sequence' => 2,
            'info_id' => 1,
            'bf_if_disp' => 1,
            'if_have_sub' => false,
            'if_sort' => false,
            'if_have_paper' => false,
            'if_show_score' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        Sclass::create([
            'color' => '#00FF00',
            'name_e' => 'Bundesliga',
            'name_es' => 'Bundesliga',
            'name_s' => 'BL',
            'kind' => 1,
            'mode' => 1,
            'count_round' => 34,
            'curr_round' => 1,
            'curr_match_season' => '2024-2025',
            'sclass_pic' => 'https://upload.wikimedia.org/wikipedia/vi/f/f9/Bundesliga_logo_%282017%29.png',
            'if_stop' => 0,
            'count_group' => 1,
            'bf_simply_disp' => 1,
            'sclass_sequence' => 3,
            'info_id' => 1,
            'bf_if_disp' => 1,
            'if_have_sub' => false,
            'if_sort' => false,
            'if_have_paper' => false,
            'if_show_score' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        Sclass::create([
            'color' => '#FF5733',
            'name_e' => 'Serie A',
            'name_es' => 'Serie A',
            'name_s' => 'SA',
            'kind' => 0,
            'mode' => 1,
            'count_round' => 38,
            'curr_round' => 1,
            'curr_match_season' => '2024-2025',
            'sclass_pic' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Serie_A_logo_2022.svg/596px-Serie_A_logo_2022.svg.png',
            'if_stop' => 0,
            'count_group' => 1,
            'bf_simply_disp' => 1,
            'sclass_sequence' => 4,
            'info_id' => 1,
            'bf_if_disp' => 1,
            'if_have_sub' => false,
            'if_sort' => false,
            'if_have_paper' => false,
            'if_show_score' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        
        Sclass::create([
            'color' => '#FFC300',
            'name_e' => 'Ligue 1',
            'name_es' => 'Ligue 1',
            'name_s' => 'L1',
            'kind' => 1,
            'mode' => 1,
            'count_round' => 38,
            'curr_round' => 1,
            'curr_match_season' => '2024-2025',
            'sclass_pic' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Ligue1.svg/1200px-Ligue1.svg.png',
            'if_stop' => 0,
            'count_group' => 1,
            'bf_simply_disp' => 1,
            'sclass_sequence' => 5,
            'info_id' => 1,
            'bf_if_disp' => 1,
            'if_have_sub' => false,
            'if_sort' => false,
            'if_have_paper' => false,
            'if_show_score' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        
        Sclass::create([
            'color' => '#900C3F',
            'name_e' => 'Serie A Brazil',
            'name_es' => 'Serie A Brazil',
            'name_s' => 'SA',
            'kind' => 0,
            'mode' => 1,
            'count_round' => 38,
            'curr_round' => 1,
            'curr_match_season' => '2024-2025',
            'sclass_pic' => 'https://upload.wikimedia.org/wikipedia/vi/4/42/Campeonato_Brasileiro_S%C3%A9rie_A_logo.png',
            'if_stop' => 0,
            'count_group' => 1,
            'bf_simply_disp' => 1,
            'sclass_sequence' => 6,
            'info_id' => 1,
            'bf_if_disp' => 1,
            'if_have_sub' => false,
            'if_sort' => false,
            'if_have_paper' => false,
            'if_show_score' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        
        Sclass::create([
            'color' => '#9B59B6',
            'name_e' => 'Eredivisie',
            'name_es' => 'Eredivisie',
            'name_s' => 'ER',
            'kind' => 1,
            'mode' => 1,
            'count_round' => 34,
            'curr_round' => 1,
            'curr_match_season' => '2024-2025',
            'sclass_pic' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Eredivisie_nieuw_logo_2017-.svg/1280px-Eredivisie_nieuw_logo_2017-.svg.png',
            'if_stop' => 0,
            'count_group' => 1,
            'bf_simply_disp' => 1,
            'sclass_sequence' => 7,
            'info_id' => 1,
            'bf_if_disp' => 1,
            'if_have_sub' => false,
            'if_sort' => false,
            'if_have_paper' => false,
            'if_show_score' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        
        Sclass::create([
            'color' => '#27AE60',
            'name_e' => 'Primeira Liga',
            'name_es' => 'Primeira Liga',
            'name_s' => 'PL',
            'kind' => 1,
            'mode' => 1,
            'count_round' => 34,
            'curr_round' => 1,
            'curr_match_season' => '2024-2025',
            'sclass_pic' => 'https://upload.wikimedia.org/wikipedia/vi/e/ef/S%C3%BCper_Lig_logo.png',
            'if_stop' => 0,
            'count_group' => 1,
            'bf_simply_disp' => 1,
            'sclass_sequence' => 8,
            'info_id' => 1,
            'bf_if_disp' => 1,
            'if_have_sub' => false,
            'if_sort' => false,
            'if_have_paper' => false,
            'if_show_score' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        
        Sclass::create([
            'color' => '#3498DB',
            'name_e' => 'Super Lig',
            'name_es' => 'Super Lig',
            'name_s' => 'SL',
            'kind' => 0,
            'mode' => 1,
            'count_round' => 34,
            'curr_round' => 1,
            'curr_match_season' => '2024-2025',
            'sclass_pic' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/S%C3%BCper_Lig_Logo.svg/1200px-S%C3%BCper_Lig_Logo.svg.png',
            'if_stop' => 0,
            'count_group' => 1,
            'bf_simply_disp' => 1,
            'sclass_sequence' => 9,
            'info_id' => 1,
            'bf_if_disp' => 1,
            'if_have_sub' => false,
            'if_sort' => false,
            'if_have_paper' => false,
            'if_show_score' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        Sclass::create([
            'color' => '#F39C12',
            'name_e' => 'Süper Lig',
            'name_es' => 'Süper Lig',
            'name_s' => 'SL',
            'kind' => 1,
            'mode' => 1,
            'count_round' => 34,
            'curr_round' => 1,
            'curr_match_season' => '2024-2025',
            'sclass_pic' => 'https://upload.wikimedia.org/wikipedia/vi/e/ef/S%C3%BCper_Lig_logo.png',
            'if_stop' => 0,
            'count_group' => 1,
            'bf_simply_disp' => 1,
            'sclass_sequence' => 10,
            'info_id' => 1,
            'bf_if_disp' => 1,
            'if_have_sub' => false,
            'if_sort' => false,
            'if_have_paper' => false,
            'if_show_score' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        
        
    }
}

